### PR TITLE
Add `wiremock-spring-boot` to external resources

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
Context: https://twitter.com/TomAkehurst/status/1630324598158835712

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
+1 from me. And  thank you!

**Comment by oleg-nenashev** [comment]
Merging it. Looks like we still need to sort out CD for the website, but it will be published eventually

**Comment by maciejwalkowiak** [comment]
Awesome! Thank you!

**Comment by maciejwalkowiak** [comment]
@oleg-nenashev perhaps you can also consider adding a link to this library at https://wiremock.org/docs/spring-boot/ ?

**Pull request merged**
